---
- name: Setup All timezone
  hosts: CentOS
  gather_facts: no
  become: yes

  tasks:
    - name: set timezone to Asia/Seoul
      timezone: name=Asia/Seoul

# ans CentOS -m shell -a "timedatectl | grep 'Time zone'" -k
# 국제 표준시에서 한국 표준시로 변경이 되었는 지 확인