---
- name: Install nginx on nodes
  hosts: nodes
  become: yes
  vars:
    - lnx_name: "{{ 'CentOS' if ansible_distribution == 'CentOS'
                     else 'Ubuntu' if ansible_distribution == 'Ubuntu'
                     else 'Just Linux' }}"
  tasks:
    - name: nginx for any linux
      include tasks: "{{ lnx_name }}.yml"